apiVersion: v1
kind: Service
metadata:
  name: authentication-medium
  namespace: authentication-app
spec:
  selector:
    app: authentication
    node: medium
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001
  type: NodePort
