apiVersion: v1
kind: Service
metadata:
  name: db-medium
  namespace: authentication-app
spec:
  selector:
    app: postgres
    node: medium
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
