apiVersion: v1
kind: Service
metadata:
  name: db-nano
  namespace: authentication-app
spec:
  selector:
    app: postgres
    node: nano
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
